### ISSUE TITLE
Could not find package hacklee/laravel5-php-redis at any version...

### ISSUE THREAD

**Issue by heisian** [hacklee/laravel5-php-redis#2]
Running:

```
composer require hacklee/laravel5-php-redis
```

Produces:

```
[InvalidArgumentException]                                                             
Could not find package hacklee/laravel5-php-redis at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability  
```

I think to fix this problem you need to run:

```
git tag 1.0
git push origin --tags
```

And you should see a 1.0 version (in addition to dev-master) in your Packagist page, as long as you're Packagist account is set to auto-update with a GitHub push.

Here's an example of one of mine:
https://packagist.org/packages/revolverobotics/helper-tools

`Note:` I am aware that adding `"hacklee/laravel5-php-redis": "dev-master"` to composer.json works, but would prefer `composer require` to work as well as have versioning.

**Comment by hacklee** [comment]
thank you ，fixed

**Comment by heisian** [comment]
awesome, thank you!
